# Experiment overview
name: "class-annotation"
type: ClassAnnotation

# Design
num_participants: 8

# Appearance
stimulus_area_size: [1100, 900]
font_monospaced: false
background_color: [204, 204, 204]
margin: 50
font_size: 25
line_spacing: 2.5

# Labels
labels: [positive, neutral, negative]
label_texts: ["[<] positive", "[v] neutral", "[>] negative"]
label_option_keys: [LEFT, DOWN, RIGHT]
label_confirm_key: SPACE

# Questions
questions:
- stem: "How confident are you in your label choice?"
  options: ["Very confident", "Somewhat confident", "Not confident at all"]
question_confirm_key: SPACE

# Breaks between items
breaks_after: 3
