# Experiment overview
name: "multi-page-reading"
type: MultiPageReading

# Design
num_participants: 8

# Appearance
stimulus_area_px: [ 1920, 1200]
font_monospaced: true
background_color: [204, 204, 204]
margin_px: 50
font_size: 25
line_spacing: 2.5

# Questions
question_layout: diamond
confirm_key: SPACE

# Breaks between items
breaks_after: 4

# Eye-tracker setup
tracking_mode: "remote"