title: eidon
description: A toolkit for implementing eye-tracking experiments
# theme: just-the-docs

url: https://saeub.github.io
baseurl: /eidon
logo: "/assets/images/logo.svg"
favicon_ico: "/assets/images/favicon.png"

mermaid:
  version: 11.12.0

aux_links:
  Source code: https://github.com/saeub/eidon

# GitHub Pages
plugins:
- jekyll-remote-theme
remote_theme: just-the-docs/just-the-docs@v0.12.0
